### ISSUE TITLE
Failed to build duplicate symbol

### ISSUE THREAD

**Issue by Loukious** [crdroidandroid/android_kernel_xiaomi_sm8150#1]
I'm trying to build the kernel from source and I'm getting this error.

<details>
<summary>Details</summary>

`
ld.lld: error: duplicate symbol: htc_start
>>> defined at htc_hst.c:327 (../drivers/net/wireless/ath/ath9k/htc_hst.c:327)
>>>            drivers/net/wireless/ath/ath9k/htc_hst.o:(htc_start) in archive built-in.o
>>> defined at htc.c:771 (../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/htc/htc.c:771)
>>>            drivers/staging/qca-wifi-host-cmn/htc/htc.o:(.text+0xB50) in archive built-in.o

ld.lld: error: duplicate symbol: htc_stop
>>> defined at htc_hst.c:322 (../drivers/net/wireless/ath/ath9k/htc_hst.c:322)
>>>            drivers/net/wireless/ath/ath9k/htc_hst.o:(htc_stop) in archive built-in.o
>>> defined at htc.c:880 (../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/htc/htc.c:880)
>>>            drivers/staging/qca-wifi-host-cmn/htc/htc.o:(.text+0xE60) in archive built-in.o

ld.lld: error: duplicate symbol: htc_connect_service
>>> defined at htc_hst.c:246 (../drivers/net/wireless/ath/ath9k/htc_hst.c:246)
>>>            drivers/net/wireless/ath/ath9k/htc_hst.o:(htc_connect_service) in archive built-in.o
>>> defined at htc_services.c:93 (../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/htc/htc_services.c:93)
>>>            drivers/staging/qca-wifi-host-cmn/htc/htc_services.o:(.text+0x20) in archive built-in.o
make[1]: *** [/root/og/android_kernel_xiaomi_sm8150/Makefile:1220: vmlinux] Error 1
make: *** [Makefile:153: sub-make] Error 2
`

</details>
I've solved it using this [commit](https://github.com/Loukious/android_kernel_xiaomi_sm8150/commit/d3f89a8690213e277c2ef75abe566198bac57894) but the phone won't boot. These are kernel logs https://pastebin.com/yqiTspfK
I'm using this defconfig
https://github.com/Loukious/android_kernel_xiaomi_sm8150/blob/13.0/arch/arm64/configs/kali_defconfig

**Comment by neobuddy89** [comment]
did vayu_defconfig built fine?

**Comment by Loukious** [comment]
> did vayu_defconfig built fine?

No. Seems like I was unable to build it using that.
` 
LTO     vmlinux.o
../scripts/link-vmlinux.sh: line 102: 978564 Killed                  ${LD} ${LDFLAGS} -r -o ${1} $(lto_lds) ${objects}
make[1]: *** [/root/og/android_kernel_xiaomi_sm8150/Makefile:1220: vmlinux] Error 137
make: *** [Makefile:153: sub-make] Error 2
`
Weird because the kill reason is "Out of memory" and I allocated 16GB of ram to it. I'll try adding more and see what happens.
Edit: I've tried allocated 26GB and it still couldn't build it.

**Comment by Loukious** [comment]
For anyone else having the same issue, updating to latest Google Clang fixed it.
