### ISSUE TITLE
Non-KSU kernel version?

### ISSUE THREAD

**Issue by 33KK** [crdroidandroid/android_kernel_xiaomi_sm8150#6]
Seems like it conflicts with APatch

Alternatively please tell me if/how its possible to build this with KSU disabled in Kconfig without downloading the entire ROM tree and building the entire ROM

**Comment by ghost** [comment]
Why you want to use APatch if it's almost the same as KernelSU?

**Comment by ghost** [comment]
Well if you don't want KSU you can revert the commit and build by yourself, just download the source:

```
git clone --depth=1 https://github.com/crdroidandroid/android_kernel_xiaomi_sm8150.git
```

build config
```
make O=out ARCH=arm64 vendor/sm8150-perf_defconfig vendor/xiaomi/sm8150-common.config vendor/debugfs.config vendor/xiaomi/{CODENAME}.config
```

Replace "{CODENAME}" by the device codename, see: https://github.com/crdroidandroid/android_kernel_xiaomi_sm8150/tree/14.0/arch/arm64/configs/vendor/xiaomi

Now disable KSU:
```
scripts/config --file out/.config -d CONFIG_KSU
```

Also, if you don't have a PC with >32GB RAM, turn on ThinLTO or disable LTO:
```
scripts/config --file out/.config -e CONFIG_THINLTO
```
or
```
scripts/config --file out/.config -d CONFIG_LTO
scripts/config --file out/.config -d CONFIG_LTO_CLANG
scripts/config --file out/.config -e CONFIG_LTO_NONE
```

build kernel
```
make O=out ARCH=arm64 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld LLVM=1 LLVM_IAS=1 CC=clang CROSS_COMPILE=aarch64-linux-gnu- all
```

**Comment by 33KK** [comment]
> Why you want to use APatch if it's almost the same as KernelSU?

Mostly because I saw that APatch just uses magiskpolicy instead of a custom thing. Also seems like a better solution long term since it supports quite a big range of kernel versions and doesn't require using custom kernels/ROM developers baking it into the kernel.

Thanks for the build instructions, I'll try it later
